In [1]:
from ddsp.encoders import ResNetAutoencoder
from ddsp.model import DDSP
import torch
import librosa as li

#model = ResNetAutoencoder()

In [2]:
x, _ = li.load('idmt_dataset4/acoustic_mic_fast_classical_classical_1_80BPM.wav', sr=16000)

In [3]:
model = DDSP()

In [4]:
x = torch.tensor(x)
x = x.unsqueeze(0)
out = model(x)

[W NNPACK.cpp:64] Could not initialize NNPACK! Reason: Unsupported hardware.


In [5]:
out.shape

torch.Size([1, 64000, 1])

In [ ]:
x = torch.tensor(x)
x = x.unsqueeze(0)
model(x)

In [5]:
import torchaudio.transforms as T

spec = T.MelSpectrogram(
            sample_rate=16000,
            n_fft=2048,
            n_mels=64,
            hop_length=int(2048 * (1.0 - 0.75)),
            f_min=20.0,
            f_max=8000.0, 
        )

In [9]:
out = spec(x[:, :16000])

In [10]:
out.shape

torch.Size([1, 64, 32])

In [1]:
import os

def list_files(directory):
    file_list = []
    
    if os.path.isdir(directory):
        for file in os.listdir(directory):
            file_path = os.path.join(directory, file)
            if os.path.isfile(file_path) and file_path.split(".")[-1]=="wav":
                file_list.append(file_path)
    else:
        print(f"The directory '{directory}' does not exist.")
    
    return file_list


def change_file_name(old_path, new_name, new_directory=None):
    try:
        directory, filename = os.path.split(old_path)
        if new_directory:
            n = new_name+filename
            new_path = os.path.join(new_directory, n)
        else:
            new_path = os.path.join(directory, new_name)
        
        os.rename(old_path, new_path)
        
    except FileExistsError:
        print(f"A file with the name '{new_name}' already exists.")
    except Exception as e:
        print(f"An error occurred: {str(e)}")

In [5]:
#nought = ["career_sg", "ibaneze_2820","acoustic_pickup", "acoustic_mic"]
nought = ["acoustic_pickup"]

first = ["fast", "slow"]
second = ["classical", "country_folk", "jazz", "latin", "metal", "pop", "reggae_ska", "rock_blues"]
third = ["audio"]

for n in nought:
    for f in first:
        for s in second:
            for aud in third:
                pth = f"dataset4_copy/{n}/{f}/{s}/{aud}"
                files = list_files(pth)
                for fl in files:
                    new = f"{n}_{f}_{s}_"
                    change_file_name(fl, new, new_directory="idmt_dataset4_acoustic_pickup")


In [6]:
import torch

In [13]:
m = torch.ones(2,3,4)
n = 2*torch.ones(2,3,4,6)

s = torch.einsum("bsp,bspa->bsp",m,n)

In [14]:
s

tensor([[[12., 12., 12., 12.],
         [12., 12., 12., 12.],
         [12., 12., 12., 12.]],

        [[12., 12., 12., 12.],
         [12., 12., 12., 12.],
         [12., 12., 12., 12.]]])

In [11]:
m

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [12]:
n

tensor([[[[2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.]],

         [[2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.]],

         [[2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.]]],


        [[[2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.]],

         [[2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.]],

         [[2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.]]]])